version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:8080"
    tty: true
    environment:
      TZ: Asia/Tokyo

  db:
    container_name: db
    image: mysql:8.0.15
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    cap_add:
      - SYS_NICE